### ISSUE TITLE
・（中黒）があると先頭行、または、次の行末に移動する

### ISSUE THREAD

**Issue by adachij2002** [kaitoy/japanese-word-selection#1]
例えば、以下のような文章があるとします。
- "・"の前でCtrl＋→を押した場合、"Q"の後ろに移動してしまう。
- "・"の後ろでCtrl＋←を押した場合、"メモ"の前に移動してしまう。

例）
メモ

・ショートカット
  アプリケーションを終了する：Command＋Q

**Comment by kaitoy** [comment]
修正版v0.3.1をリリースしました。(バージョン付け間違えた…)
試してみてください。

**Comment by adachij2002** [comment]
条件によって動作がおかしくなるようです。
1. 改行がLFの場合
   - "ショートカット"の前の行でCtrl＋→を押すと、"ショートカット"の次の行に移動してしまう
   - "ショートカット"の次の行でCtrl＋←を押すと、"メモ"の前に移動してしまう
2. 改行がCRLFの場合
   - Ctrl＋→を押しても、行末から次の行に移動しない
3. "■"が含まれる場合
   - "■"の前でAlt＋→を押すと、"アプリケーション"の行頭に移動してしまう
   - "■"の後ろでAlt＋←を押しても、カーソルが移動しない
4. タブが含まれる場合
   - "タブ"＋"アプリケーション"の前でCtrl＋→を押すと、行末に移動してしまう
   - "■"の前でAlt＋→を押すと、"タブ"＋"ショートカット"の行頭に移動してしまう

例）
メモ

■ショートカット／ジェスチャー

```
・ショートカット

    アプリケーションを終了する：Command＋Q
```

**Comment by kaitoy** [comment]
■は全く未対応でした。
改行やタブやスペースは特別扱いしないとだめかもしれないです。
もうちょっと見てみます。

**Comment by kaitoy** [comment]
Alt＋→とAlt＋←はサブワードに対する操作ですが、日本語のサブワード対応は難しいのでとりあえず諦めます。それ以外は0.4.0で対応します。
